version: '3.8'

services:
  api:
    build: .
    container_name: signup-flow-api
    env_file:
      - .env
    ports:
      - "8080:8080"
    command: sh -c "yarn db:generate && yarn db:push && yarn start:prod" 